Repository NgoThiVanGiang/2008299410_Snake_game, pull requests merged in 2025-08, with the labels that each got.

#18 add commit conventions
  COMMIT_CONVENTIONS.md
Labels: documentation, feature

#43 add comments for functions
  SnakeGame.cpp
Labels: documentation

#53 add generateFood
  SnakeGame.cpp
Labels: feature

#54 Revert "add generateFood" due to wrong account
  SnakeGame.cpp
Labels: bug

#63 add drawGame
  SnakeGame.cpp
Labels: feature

#64 add draw game border
  SnakeGame.cpp
Labels: feature

#65 add feature snake body
  SnakeGame.cpp
Labels: feature

#66 update screenshots section
  README.md
Labels: enhancement

#71 introduction and guide in english and vietnamese
  README.md
  README_VI.md
Labels: documentation

#67 add review process
  CONTRIBUTING.md
Labels: feature
